# Adults - fishery-independent  

SEAMAP info here  




## About

**Input `.qmd` file** for this section was: **`r xfun::with_ext(knitr::current_input(), "qmd")`** and can be found in the main directory.  

**Input data file(s)** - in `data/intermediate/adultSeamap_dfs.RData` (the single `.RData` file contains multiple data frames):

-   `seamap` - the unfiltered data frame
-   `adsm_wide`
-   `adsm_long`


**Modifications to data:**



**Generated data file(s):**  - fully processed files are in the `data/processed` directory:  

-  `juvenile_bySurveyAndMonth.csv`, in the subfolder `moreDetailed`, is summarized to species and month within year, by survey.  
-  `juvenile_bySurveyAndShrimpYear.csv`, in the subfolder `moreDetailed`, is summarized to species and shrimp year, by survey. 
-  `juvenile_byShrimpYear.csv` is summarized to species and shrimp year, as the average shrimp-year abundance across the two surveys. This is the file that will be used in further analyses.  

**Other notes about data:**

- none